### ISSUE TITLE
How do you preprocess data?

### ISSUE THREAD

**Issue by lsjAI** [KSH0660/BrainTumor#1]
I want to know how you preprocess data, such as how to set the window level and width of brats data. Could you share with me the data you have processed? Or can you provide a reference data processing script? Thank you.

**Comment by KSH0660** [comment]
Hello @lsjAI
Sorry for late reply.
We uploaded the preprocess code. (named nii2png.m)

**Comment by lsjAI** [comment]
> 

Thank you!!
