### ISSUE TITLE
where is the tumor masks come from?

### ISSUE THREAD

**Issue by JarvisKevin** [KSH0660/BrainTumor#3]
As 2.A. depicted, The concentric circles are generated from the tumor masks...
I want to ask the input image is MR Images of Normal Brain, so where is the tumor masks come from? from other abnormal image?

**Comment by KSH0660** [comment]
Hi, thanks for your questions. Circles can be made by simple matlab or python code. 
I made concentric circle images by myself in matlab code at inference.
In training, they were made by abnormal tumor brain as depicted in Fig.1.
